# .github/workflows/auto-assistant.yml

name: Auto Assistant Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  summarize-commit:
    runs-on: ubuntu-latest

    # UPDATED: Use the official Bun image which includes Node.js and npm
    container:
      image: oven/bun:1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Gemini-CLI
        run: npm install -g gemi

      # This step will now succeed because Bun is available in the container
      - name: Generate Commit Summary
        run: |
          gemi -p "You are a helpful assistant writing release notes. Briefly summarize the following commit message in a single, clear sentence: ${{ github.event.head_commit.message }}" -k ${{ secrets.GEMINI_API_KEY }}