# .github/workflows/auto-assistant.yml

name: Gemini CLI Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is named "run-gemini-cli"
  run-gemini-cli:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sets up a Node.js environment for installing the CLI
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a current LTS version of Node.js

      # Installs the gemini-cli package globally
      - name: Install Gemini-CLI
        run: npm install -g gemini-cli

      # Runs a simple Gemini prompt
      - name: Run Gemini Prompt
        run: gemini -p "Explain what a GitHub Action is in one sentence."
        env:
          # Pass the API key to the command as an environment variable
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}