# .github/workflows/code-assistant.yml

name: 'Analyze Commit on Push'

# Trigger the workflow on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  analyze-commit:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout repository to access commit history
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      # 2. Set up Node.js environment (v20 or higher is required)
      - name: 'Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Get the latest commit message
      - name: 'Get latest commit message'
        id: commit
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      # 4. Analyze the commit by running the CLI with npx
      - name: 'Analyze Commit with Gemini'
        run: |
          npx @google/gemini-cli "Classify the following commit message. Is it a feature, fix, chore, docs, or test? Explain your reasoning in one sentence. Commit Message: ${{ steps.commit.outputs.message }}"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}